chore: integrate husky & lintstaged & update  gitignore
Crossbell-Box/xLog-mobile pull request #60
Opened 2023-05-07 03:49 UTC by SteveYuOWO

<img width="911" alt="image" src="https://user-images.githubusercontent.com/41619339/236656559-2b54972a-d1b1-44aa-b629-13f8b97449db.png">
Code is not formatted correctly by eslint. 
Adding lintstaged to automatically format code before committing

2023-05-07 06:02 UTC, dohooo requested changes
Thx for your contribution! Could you change the target to staging? 🤗

2023-05-07 06:02 UTC, dohooo commented on app.config.ts
Hmm, we just need to use the .env.common file currently. So, I think line 6 isn't necessary.

2023-05-07 18:00 UTC, SteveYuOWO commented on app.config.ts
> Thx for your contribution! Could you change the target to staging? 🤗

Thanks for your reply. Target has been changed to staging.

2023-05-07 18:00 UTC, SteveYuOWO commented on app.config.ts
> Hmm, we just need to use the .env.common file currently. So, I think line 6 isn't necessary.

okay, `.env` configuration has been removed

2023-05-08 02:03 UTC, dohooo approved these changes

2023-05-08 02:03 UTC, merged